[profile.default]
src = "src"
ast = true
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
ffi = true
viaIR = true
fs_permissions = [{ access = "read", path = "./broadcast" },{ access = "read", path = "./out" }]
optimizer_runs = 200
eth_rpc_timeout = 300
solc_version = "0.8.26"

[etherscan]
dbc-mainnet = { key = "abc", url = "https://rpc.dbcwallet.io", chain = "19880818" }
dbc-testnet = { key = "abc", url = "https://rpc-testnet.dbcwallet.io", chain = "19850818" }
local-testnet = { key = "abc", url = "http://localhost:7545", chain = "5777" }


[rpc_endpoints]
dbc-mainnet = "https://rpc2.dbcwallet.io"
dbc-testnet = "https://rpc-testnet.dbcwallet.io"
bsc-testnet = "https://data-seed-prebsc-1-s3.binance.org:8545"
local-testnet = { key = "abc", url = "http://localhost:7545", chain = "5777" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
